import './sass/style.scss';
import './blocks/swiper/swiper';
import './blocks/header/header';
import './blocks/menu/menu';
import './blocks/callback/callback';
import './blocks/feedback/feedback';
import './blocks/brands/brands';
import './blocks/types/types';
import './blocks/main/main';
